/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicioFactura;

import Home.home;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author tatip
 */
public class Ejer1Factu extends javax.swing.JFrame {

    /**
     * Creates new form Ejer1Factu
     */
    public Ejer1Factu() {
        initComponents();
    }
    
  
     List<Factura> lista = new ArrayList<Factura>();
     

       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtResultado = new LIB.FSTexFieldMD();
        txtImporte = new LIB.FSTexFieldMD();
        btnMenuPrincipal = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setText("Ejercicio 1 Factura");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel2.setText("Resultado del filtro:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        txtResultado.setForeground(new java.awt.Color(0, 0, 0));
        txtResultado.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtResultado.setPlaceholder("Resultado");
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        txtImporte.setForeground(new java.awt.Color(0, 0, 0));
        txtImporte.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtImporte.setPlaceholder("Importe");
        txtImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImporteActionPerformed(evt);
            }
        });
        jPanel1.add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        btnMenuPrincipal.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnMenuPrincipal.setText("Casa");
        btnMenuPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuPrincipalMouseClicked(evt);
            }
        });
        jPanel1.add(btnMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 120, 40));

        btnGuardar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnGuardar.setText("Generar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 120, 40));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 13)); // NOI18N
        jLabel3.setText("Ingrese el importe para el filtro:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
       Factura f = new Factura("ordenador", 1000);
        Factura f2 = new Factura("movil", 300);
        Factura f3 = new Factura("impresora", 200);
        Factura f4 = new Factura("imac", 1500);

        lista.add(f);
        lista.add(f2);
        lista.add(f3);
        lista.add(f4);
        

        Factura facturaFiltro = lista.stream().filter(elemento -> elemento.getImporte() >= Double.valueOf(txtImporte.getText())).findFirst().get();
        
        txtResultado.setText(String.valueOf(facturaFiltro.getImporte()));
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImporteActionPerformed

    private void btnMenuPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuPrincipalMouseClicked
        home h = new home ();
        
        h.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnMenuPrincipalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejer1Factu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejer1Factu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejer1Factu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejer1Factu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejer1Factu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private LIB.FSTexFieldMD txtImporte;
    private LIB.FSTexFieldMD txtResultado;
    // End of variables declaration//GEN-END:variables
}
