/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicioFactura;

import Home.home;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;

/**
 *
 * @author tatip
 */
public class Ejer2Factura extends javax.swing.JFrame {

    /**
     * Creates new form Ejer2Factura
     */
    public Ejer2Factura() {
        initComponents();
    }

    List<Factura> lista = new ArrayList<Factura>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUnica = new LIB.FSTexFieldMD();
        jLabel1 = new javax.swing.JLabel();
        txtImporte1 = new LIB.FSTexFieldMD();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtIteracion = new LIB.FSTexFieldMD();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUnica.setForeground(new java.awt.Color(0, 0, 0));
        txtUnica.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtUnica.setPlaceholder("Unica");
        txtUnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnicaActionPerformed(evt);
            }
        });
        jPanel1.add(txtUnica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setText("Ejercicio 2 Factura");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        txtImporte1.setForeground(new java.awt.Color(0, 0, 0));
        txtImporte1.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtImporte1.setPlaceholder("Importe");
        txtImporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImporte1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtImporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 40));

        jButton2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jButton2.setText("Casa");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 120, 40));

        txtIteracion.setForeground(new java.awt.Color(0, 0, 0));
        txtIteracion.setBordeColorFocus(new java.awt.Color(0, 0, 0));
        txtIteracion.setPlaceholder("Iteración");
        txtIteracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIteracionActionPerformed(evt);
            }
        });
        jPanel1.add(txtIteracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnicaActionPerformed

    private void txtImporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImporte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImporte1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        home h = new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Factura f = new Factura("ordenador", 1200);
        Factura f2 = new Factura("movil", 300);
        Factura f3 = new Factura("impresora", 200);
        Factura f4 = new Factura("imac", 1500);

        lista.add(f);
        lista.add(f2);
        lista.add(f3);
        lista.add(f4);

        Predicate<Factura> predicado = new Predicate<Factura>() {

            String imp = txtImporte1.getText();

            @Override
            public boolean test(Factura f) {

                txtIteracion.setText(" iteracion ");

                double imp2 = Double.valueOf(imp);

                return f.getImporte() > imp2;

            }

        };

        Factura facturaFiltro = lista.stream().filter(predicado).findFirst().get();

        txtUnica.setText("UNICA" + String.valueOf(facturaFiltro.getImporte()));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIteracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIteracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIteracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejer2Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejer2Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejer2Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejer2Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejer2Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private LIB.FSTexFieldMD txtImporte1;
    private LIB.FSTexFieldMD txtIteracion;
    private LIB.FSTexFieldMD txtUnica;
    // End of variables declaration//GEN-END:variables
}
