/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciostream;

import Home.home;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 *
 * @author tatip
 */
public class Personash extends javax.swing.JFrame {

    /**
     * Creates new form Personash
     */
    public Personash() {
        initComponents();
        
        tiempoEjecucion();
        
    }

    List<Persona> personas = new ArrayList<>();

    public void lista() {
        try {

            List<String> lineas = Files.readAllLines(Paths.get("C:\\Users\\tatip\\Desktop\\listaPersonas.txt"));
            lineas.stream().map(linea -> linea.split(" ")).filter(datos -> datos.length >= 3).forEach(datos -> {
                String nombre = datos[0];
                String apellido1 = datos[1];
                String apellido2 = datos[2];

                Persona persona = new Persona();
                persona.setNombre(nombre);
                persona.setApellido1(apellido1);
                persona.setApellido2(apellido2);

                personas.add(persona);

            });

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void tiempoEjecucion() {

        long tiempoInicio = System.currentTimeMillis();
        
        long tiempoFin = System.currentTimeMillis();

        long tiempoTranscurrido = (tiempoFin - tiempoInicio) / 1000;

        String tiempoTranscurridoStg = String.valueOf(tiempoInicio);

        txtTiempo.setText(tiempoTranscurridoStg);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListaPersonas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnListaPersonas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarPersona = new javax.swing.JButton();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtBuscaNombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultadoBusqueda = new javax.swing.JTextArea();
        btnBuscarPersona1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtListaOrdenada = new javax.swing.JTextArea();
        btnListaOrdenada = new javax.swing.JButton();
        txtTiempo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtListaPersonas.setEditable(false);
        txtListaPersonas.setColumns(20);
        txtListaPersonas.setRows(5);
        jScrollPane1.setViewportView(txtListaPersonas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 55, 240, 230));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista Ordenada por Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        btnListaPersonas.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnListaPersonas.setText("Cargar Lista");
        btnListaPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(btnListaPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 240, 40));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lista de Personas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnBuscarPersona.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnBuscarPersona.setText("Buscar Persona");
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, 40));

        txtApellidoP.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        txtApellidoP.setForeground(new java.awt.Color(153, 153, 153));
        txtApellidoP.setText("Ingrese el apellido paterno");
        txtApellidoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoPMouseClicked(evt);
            }
        });
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 290, 40));

        txtApellidoM.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        txtApellidoM.setForeground(new java.awt.Color(153, 153, 153));
        txtApellidoM.setText("Ingrese el apellido materno");
        txtApellidoM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMMouseClicked(evt);
            }
        });
        txtApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 290, 40));

        txtBuscaNombre.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        txtBuscaNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscaNombre.setText("Ingrese el nombre");
        txtBuscaNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscaNombreMouseClicked(evt);
            }
        });
        txtBuscaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 290, 40));

        txtResultadoBusqueda.setEditable(false);
        txtResultadoBusqueda.setColumns(20);
        txtResultadoBusqueda.setRows(5);
        jScrollPane2.setViewportView(txtResultadoBusqueda);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 290, 40));

        btnBuscarPersona1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnBuscarPersona1.setText("Casa");
        btnBuscarPersona1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPersona1MouseClicked(evt);
            }
        });
        btnBuscarPersona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersona1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarPersona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 135, 40));

        txtListaOrdenada.setEditable(false);
        txtListaOrdenada.setColumns(20);
        txtListaOrdenada.setRows(5);
        jScrollPane3.setViewportView(txtListaOrdenada);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 240, 160));

        btnListaOrdenada.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnListaOrdenada.setText("Ordenar Lista por Nombre");
        btnListaOrdenada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaOrdenadaActionPerformed(evt);
            }
        });
        jPanel1.add(btnListaOrdenada, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 240, 40));

        txtTiempo.setEditable(false);
        txtTiempo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        txtTiempo.setForeground(new java.awt.Color(153, 153, 153));
        txtTiempo.setText("Tiempo transcurrido en el proceso");
        txtTiempo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTiempoMouseClicked(evt);
            }
        });
        txtTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiempoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 240, 40));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Buscar una Persona");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListaPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaPersonasActionPerformed

        lista();

        String listaPersonas = personas.stream().map(persona -> persona.getNombre() + " " + persona.getApellido1() + " " + persona.getApellido2()).collect(Collectors.joining("\n"));

        txtListaPersonas.setText(listaPersonas);
        
          tiempoEjecucion();

    }//GEN-LAST:event_btnListaPersonasActionPerformed

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed

        lista();

        String buscaNom = txtBuscaNombre.getText();
        String buscaApe1 = txtApellidoP.getText();
        String buscaApe2 = txtApellidoM.getText();

        Optional<Persona> personaEncontrada = personas.stream().filter(persona -> persona.getNombre().equals(buscaNom) && persona.getApellido1().equals(buscaApe1)
                && persona.getApellido2().equals(buscaApe2)).findFirst();

        personaEncontrada.ifPresentOrElse(persona -> txtResultadoBusqueda.setText("Persona encontrada: " + persona.getNombre() + " " + persona.getApellido1() + " "
                + persona.getApellido2()), () -> txtResultadoBusqueda.setText("La persona que buscas no existe."));
        
          tiempoEjecucion();

    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void txtApellidoPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoPMouseClicked
        txtApellidoP.setText("");
    }//GEN-LAST:event_txtApellidoPMouseClicked

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void txtApellidoMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMMouseClicked
        txtApellidoM.setText("");
    }//GEN-LAST:event_txtApellidoMMouseClicked

    private void txtApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMActionPerformed

    }//GEN-LAST:event_txtApellidoMActionPerformed

    private void txtBuscaNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscaNombreMouseClicked
        txtBuscaNombre.setText("");
    }//GEN-LAST:event_txtBuscaNombreMouseClicked

    private void txtBuscaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaNombreActionPerformed

    private void btnBuscarPersona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersona1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPersona1ActionPerformed

    private void btnBuscarPersona1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPersona1MouseClicked
        home h = new home();

        h.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnBuscarPersona1MouseClicked

    private void btnListaOrdenadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaOrdenadaActionPerformed

        lista();

        List<Persona> personasOrdenadas = personas.stream().sorted(Comparator.comparing(Persona::getNombre)).collect(Collectors.toList());

        String listaPersonas = personasOrdenadas.stream().map(persona -> persona.getNombre() + " " + persona.getApellido1() + " " + persona.getApellido2()).collect(Collectors.joining("\n"));

        txtListaOrdenada.setText(listaPersonas);
        
          tiempoEjecucion();

    }//GEN-LAST:event_btnListaOrdenadaActionPerformed

    private void txtTiempoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTiempoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoMouseClicked

    private void txtTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiempoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnBuscarPersona1;
    private javax.swing.JButton btnListaOrdenada;
    private javax.swing.JButton btnListaPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtBuscaNombre;
    private javax.swing.JTextArea txtListaOrdenada;
    private javax.swing.JTextArea txtListaPersonas;
    private javax.swing.JTextArea txtResultadoBusqueda;
    private javax.swing.JTextField txtTiempo;
    // End of variables declaration//GEN-END:variables
}
